security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8044/user
server:
  port: 8002
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
