spring:
  cloud:
    stream:
      bindings:
        output:
            destination:  first_topic
            content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8044/user
server:
  port: 8002

