security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8044/user
server:
  port: 8001
spring:
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: first_topic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
