server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
     server:
      native:
        searchLocations: file:///home/smayan/projects/mcrsrvcexm/microconsrv/src/main/resources/config/microsrcexm,
                         file:///home/smayan/projects/mcrsrvcexm/microconsrv/src/main/resources/config/microconsrv,
                         file:///home/smayan/projects/mcrsrvcexm/microconsrv/src/main/resources/config/microsrcorg,
                         file:///home/smayan/projects/mcrsrvcexm/microconsrv/src/main/resources/config/microzuul	

